---
title: "Quotes"
author: "Jeff Cavanagh"
date: '2020-08-02'
output: pdf_document
lastmod: '2020-08-02T19:26:43-04:00'
layout: post
highlight: no
slug: quotes
tags: []
categories: []
type: post
---

**Movies**

### Good Will Hunting

> Real loss is only possible when you love something more than you love yourself.  
- *Sean*

### Rocky Balboa

> The world ain't all sunshine and rainbows. It's a very mean and nasty place, and I don't care how tough you are, it will beat you to your knees and keep you there permanently if you let it. You, me, or nobody is gonna hit as hard as life. But it ain't about how hard ya hit. It's about how hard you can GET hit and keep moving forward. How much you can take and keep moving forward. **That's how winning is done!**  
Now if you know what you're worth then go out and get what you're worth. But ya gotta be willing to take the hits, and not pointing fingers, saying you ain't where you wanna be because of him, or her, or anybody! Cowards do that and that ain't you!  
- *Rocky Balboa*




### The Replacements

> I look at you and see two men: the man you are, and the man you ought to be. Someday those two will meet. Should make for a hell of a football player.  
- *Jimmy McGinty*

> I wish I could say something classy and inspirational, but that just wouldn't be our style.  
Pain heals, chicks dig scars, **glory**...lasts forever.   
- *Shane Falco*


