---
title: Poetry
author: Jeff Cavanagh
date: '2020-08-05'
slug: poetry
categories: []
tags: []
lastmod: '2020-08-05T15:52:14-04:00'
layout: post
highlight: no
output:
  blogdown::html_page:
    toc: true
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

# Nothing Gold Can Stay

> Nature's first green is gold,  
Her hardest hue to hold,  
Her early leaf's a flower;  
But only so an hour.  
Then leaf subsides to leaf.  
So Eden sank to grief,  
So dawn goes down to day.  
Nothing gold can stay.  
- *Robert Frost*

*** 

# The Road Not Taken

> Two roads diverged in a yellow wood,  
And sorry I could not travel both,  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  
Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear:  
Though as for that the passing there  
Had worn them really both the same,  
And both that morning equally lay  
In leaves no step had trodden black  
Oh, I kept the first for another day!  
Yet knowing how way leads on to way,  
I doubted if I should ever come back.  
I shall be telling this with a sigh  
Somewhere ages and ages hence:  
Two roads diverged in a narrow wood, and I -  
I took the one less traveled by,  
And that has made all the difference.  
- *Robert Frost*

***

