---
title: "Endgame"
author: "Jeff Cavanagh"
date: '2020-01-15'
layout: post
highlight: yes
slug: endgame
tags:
- Complex
- Upper/Lower Split
categories: 
- Full Routine
---

**I put this workout together in the summer of 2019. At its core it is an upper/lower split. The week is formatted as two iterations of a lower body day, an upper body day, and a dynamic, multifunctional day. The reps vary slightly on a bi-weekly basis depending on which movements are the primary emphasis.**

## **Week 1**
### Monday: Compound Lower Body

* *Warmup*: TRX Squat 2 x 10
* *Explosive Movement*: Box Jump 3 x 3-5 

1. Font Squat 5 x 4-6
2. TB Deadlift 3 x 8-10
3. Superset x 3
    a. Goblet Squat x 12-15
    b. DB RDLs x 10-12
    
* *Cooldown*: Mobility work / Roll Legs / Stretch

### Tuesday: Compound Upper Body

* *Warmup*: Superset x 2
    a. Plyo-pushups x 5
    b. Face Pulls x 10

* *Explosive Movement*: Push Press 3 x 3-5

1. Pullups (weighted) 4 x 4-6
2. DB Bench 4 x 4-6
3. DB Row 3 x 8-10
4. Triset x 3
    a. Standing Arnold Press x 8-10
    b. DB Hammer Curls x 6-8
    c. DB close-grip Pushups x 15-20
5. Superset x 3
    a. Inclince DB Bench x 12-15
    b. Incline Lever Rows x 10-12

* *Cooldown*: stretch/hang

### Wednesday: Sprint/Core

1. SPRINT 8
2. Landmine 180s 4 x 10-12
3. Superset x 3
    a. Standing Rollouts x 6-10
    b. Decline (weighted) Situps x 10-12
4. Superset x 3
    a. Hanging Leg Raises x 8-10
    b. Cable Crunch x 15,12,10
5. (Opt) *Finisher*: Core Tabata (1 - 2)

* *Cooldown*: stretch

#### Thursday: Uni-Lateral Lower Body

* *Warmup*: Walking Warmup

1. Front Squat Reverse Lunge 3 x 4-6
2. Single Leg Barbell RDL 3 x 8-10
3. Bulgarian Split Squat 3 x 15,12,10
4. Glute-Ham Raise 3 x 10
5. *Finisher*: Farmer's Walks (EMOM, Tabata, minute bursts)

* *Cooldown*: Mobility work / Roll Legs / Stretch

#### Friday: Uni-Lateral Upper Body

* *Warmup*: Superset x 2
    a. Plyo-pushups x 5
    b. Face Pulls x 10
  
1. One-Arm Pushups 3 x 6-10
2. Freestanding DB Row 3 x 6-8
3. Superset x 3
    a. Kneeling Banded Pushdowns x 15-30
    b. Dips x 10-12
4. Superset x 3
    a. Chinups x 6-10
    b. Smash Curl x 10-12
5. Single-Arm Overhead Press 3 x 10-12

* *Cooldown*: stretch/hang

### Saturday: Multifunctional

1. SPRINT 8
2. Complex (Pick one from list below)
3. Chinup + Pushup (10,20;8,16;6,12;4,8;2,4 for time)
4. Sprint Tabata
5. (opt) extra Tabata or full body conditioning (Sled Push, Farmers Walks, etc.)

* *Cooldown*: stretch/hang

## **Week 2**
### Monday: Compound Lower Body

* *Warmup*: Swiss Ball Leg Curl 2 x 10
* *Explosive Movement*: Power Clean 3 x 3-5 

1. TB Deadlift 5 x 4-6
2. Font Squat 3 x 8-10
3. Superset x 3
    a. DB RDLs x 12-15
    b. Goblet Squat x 10-12
    
* *Cooldown*: Mobility work / Roll Legs / Stretch

### Tuesday: Compound Upper Body

* *Warmup*: Superset x 2
    a. Plyo-pushups x 5
    b. Face Pulls x 10

* *Explosive Movement*: Push Press 3 x 3-5

1. DB Row (weighted) 4 x 4-6
2. DB Bench 3 x 8-10
3. Pullups 3 x 8-10
4. Triset x 3
    a. Standing Arnold Press x 8-10
    b. DB Hammer Curls x 6-8
    c. DB close-grip Pushups x 15-20
5. Superset x 3
    a. Incline Lever Rows x 12-15
    b. Inclince DB Bench x 10-12

* *Cooldown*: stretch/hang

### Wednesday: Sprint/Core

1. SPRINT 8
2. Landmine 180s 4 x 10-12
3. Superset x 3
    a. Standing Rollouts x 6-10
    b. Decline (weighted) Situps x 10-12
4. Superset x 3
    a. Hanging Leg Raises x 8-10
    b. Cable Crunch x 15,12,10
5. (Opt) *Finisher*: Core Tabata (1 - 2)

* *Cooldown*: stretch

#### Thursday: Uni-Lateral Lower Body

* *Warmup*: Walking Warmup

1. Single Leg Barbell RDL 3 x 6
2. Front Squat Reverse Lunge 3 x 8 - 10
3. Glute-Ham Raise 3 x 10
4. Bulgarian Split Squat 3 x 10 - 15
5. *Finisher*: Sled Push or Farmers Walks (Timed, Distance, EMOM, or Tabata)

* *Cooldown*: Mobility work / Roll Legs / Stretch

#### Friday: Uni-Lateral Upper Body

* *Warmup*: Superset x 3
    a. Plyo-pushups x 5
    b. Face Pulls x 10
  
1. One-Arm Pushups 3 x 6-10
2. Freestanding DB Row 3 x 6-8
3. Superset x 3
    a. Chinups x 6-10
    b. Smash Curl x 10-12
4. Superset x 3
    a. Kneeling Banded Pushdowns x 15-30
    b. Dips x 10-12
5. Single-Arm Overhead Press 3 x 10-12

* *Cooldown*: stretch/hang

### Saturday: Multifunctional

1. SPRINT 8
2. Complex (Pick one from list below)
3. Chinup + Pushup (10,20;8,16;6,12;4,8;2,4 for time)
4. Sprint Tabata
5. (opt) extra Tabata or full body conditioning (Sled Push, Farmers Walks, etc.)

* *Cooldown*: stretch/hang

### Complex Options

There are several format options to apply to each complex. The main idea is to pick a weight/piece of equipment and not put it down until the round is completed.

**Spartan**

1. Power Clean
2. Front Squat
3. Push Press
4. Bentover Rows
5. RDL  
* Option: Ascending Pyramid (1:5), Descending Pyramid (5:1), Asc&Desc Pyramid (1:5:1)

**Trap Bar Grind**

1. Split Squat x 5
2. RDL x 10
3. Deadlift x 10 
* Option: 3 - 4 rounds, 1 > min rest in between rounds

**Plate Swing**

1. Overhead Squat
2. Plate Swings
3. Bent Rows
4. Reverse Lunge + Twist
5. Plate Chop  
* Option: 3 rounds with 8-10 reps per exercise, 1 > min rest in between rounds

**Overtime Landmine**

1. Squat Press
2. Single-Arm Shoulder Press
3. Single-Side RDL
4. Reverse Lunges  
* Option: 3 rounds with 10 reps per exercise, 1 > min rest in between rounds

**Dynamic TRX**

1. Jump Squat
2. Muscle Up
3. Pistol Squat
4. Rows
5. Sprinter Start Jumps
6. Standing Rollouts  
* Option: 3 - 4 rounds with 10 reps per exercise, 1 > min rest in between rounds